ERROR, 07/Jun/2024 18:07:29, exception, 58091, 139692643579712, Invalid HTTP_HOST header: '216.218.226.132'. You may need to add '216.218.226.132' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/SCAP/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/SCAP/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/opt/anaconda3/envs/SCAP/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/opt/anaconda3/envs/SCAP/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '216.218.226.132'. You may need to add '216.218.226.132' to ALLOWED_HOSTS.
WARNING, 07/Jun/2024 18:07:32, log, 58091, 139692643579712, Bad Request: /.env
